# 卷积层API

In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

img = plt.imread(r"F:\Maker\Learn_Systematically\6_Deep_learning\3_Convolutional_Neural_Networks_CNN\Meeting_at_the_Peak.jpg")
print(img.shape) # [H, W, C]

img = torch.tensor(img).permute(2, 0, 1)   # [H, W, C]--->[C, H, W]

img = img.to(torch.float32).unsqueeze(0) # [C, H, W]--->[B, C, H, W]
print(img.shape)

layer = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=(3, 3), stride = 1, padding=0)
fm = layer(img)
print(fm.shape)   # (W - Kernel_size + 2Padding) / Stride + 1

(5760, 2912, 3)
torch.Size([1, 3, 5760, 2912])
torch.Size([1, 5, 5758, 2910])


# 池化层API

## ①单通道

In [2]:
import torch
import torch.nn as nn

inputs = torch.tensor([[[0, 1, 2], [3, 4, 5], [6, 7, 8]]]).float()
print(inputs.shape)

pooling = nn.MaxPool2d(kernel_size=2, stride = 1, padding=0)
print(pooling(inputs))

pooling = nn.AvgPool2d(kernel_size=2, stride=1, padding=0)
print(pooling(inputs))

torch.Size([1, 3, 3])
tensor([[[4., 5.],
         [7., 8.]]])
tensor([[[2., 3.],
         [5., 6.]]])


## ②多通道

In [3]:
import torch
import torch.nn as nn

inputs = torch.tensor([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
                       [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
                       [[11, 22, 33], [44, 55, 66], [77, 88, 99]]]).float()
print(inputs.shape)

pooling = nn.MaxPool2d(kernel_size=2, stride = 1, padding=0)
print(pooling(inputs))

pooling = nn.AvgPool2d(kernel_size=2, stride=1, padding=0)
print(pooling(inputs))

torch.Size([3, 3, 3])
tensor([[[ 4.,  5.],
         [ 7.,  8.]],

        [[50., 60.],
         [80., 90.]],

        [[55., 66.],
         [88., 99.]]])
tensor([[[ 2.,  3.],
         [ 5.,  6.]],

        [[30., 40.],
         [60., 70.]],

        [[33., 44.],
         [66., 77.]]])
