# 词嵌入

In [7]:
import jieba
import torch
import torch.nn as nn

# 分词
text = "北京冬奥的进度条已经过半，不少外国运动员在完成自己的比赛后踏上归途"
words = jieba.lcut(text)
print(words)

print("-"*50)
# 去重
un_words = list(set(words))
print(un_words)
print("-"*50)
num = len(un_words)
print(num)

# 调用embedding
embeds = nn.Embedding(num_embeddings=num, embedding_dim=3)
print(embeds(torch.tensor(4))) # 获取  '已经'  的词向量

print("-"*50)

for i,word in enumerate(un_words):
    print(word)
    print(embeds(torch.tensor(i)))

['北京', '冬奥', '的', '进度条', '已经', '过半', '，', '不少', '外国', '运动员', '在', '完成', '自己', '的', '比赛', '后', '踏上', '归途']
--------------------------------------------------
['不少', '外国', '自己', '已经', '后', '，', '比赛', '完成', '冬奥', '踏上', '进度条', '的', '归途', '北京', '过半', '运动员', '在']
--------------------------------------------------
17
tensor([-0.4581,  1.5002,  1.2783], grad_fn=<EmbeddingBackward0>)
--------------------------------------------------
不少
tensor([0.7209, 1.1293, 0.7584], grad_fn=<EmbeddingBackward0>)
外国
tensor([1.5475, 1.2086, 0.8110], grad_fn=<EmbeddingBackward0>)
自己
tensor([ 0.6979, -0.8087,  1.6910], grad_fn=<EmbeddingBackward0>)
已经
tensor([1.0610, 1.4961, 1.6215], grad_fn=<EmbeddingBackward0>)
后
tensor([-0.4581,  1.5002,  1.2783], grad_fn=<EmbeddingBackward0>)
，
tensor([-2.3490, -0.5054, -3.0921], grad_fn=<EmbeddingBackward0>)
比赛
tensor([-0.4564,  0.0665,  0.0678], grad_fn=<EmbeddingBackward0>)
完成
tensor([-1.1348, -1.5468, -0.2375], grad_fn=<EmbeddingBackward0>)
冬奥
tensor([ 0.1746, -1.9123,  